name: payment_dpo
description: "DPO Pay checkout gateway plugin for wrteam_payment."
version: 0.0.1
homepage:
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  payment_core:
    path: ../payment_core
  payment_webview_core:
    path: ../payment_webview_core
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
